#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Aki Moto
# SPDX-License-Identifier: BSD-3-Clause
import sys

ans = 0

for line in sys.argv[1:]:
    try:
        ans += int(line)
    except:
        ans += 0

print(ans)
